package main

import (
	"database/sql"
	"fmt"
	_ "github.com/lib/pq"
	"log"
)

func createBalance(db *sql.DB) {
	query := `CREATE TABLE IF NOT EXISTS Balance (
		   id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		   user_id varchar(255) NOT NULL,
		   balance integer
  	)`
	_, err := db.Exec(query)
	if err != nil {
		log.Fatalln("Create balance", err)
	}

	//display method
	rows, err := db.Query("SELECT * FROM Balance")
	if err != nil {
		log.Fatalln(err)
	}
	defer rows.Close()

	for rows.Next() {
		var id string
		var balance int
		err = rows.Scan(&id, &balance)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(id, balance)
		break
	}
}

func createTables() {
	connStr := "user=hardella password=123 dbname=avito sslmode=disable"
	db, err := sql.Open("postgres", connStr)
	if err != nil {
		log.Fatalln(err)
	}
	if err = db.Ping(); err != nil {
		log.Fatalln(err)
	}
	defer db.Close()
	log.Println("Connected to the database")

	createBalance(db)
}

func main() {
	createTables()
}
